name: Build and Test

# on: push

on: workflow_call

env:
  PACKAGE_GITHUB_TOKEN: ${{ secrets.PACKAGE_GITHUB_TOKEN }}

jobs:
  install-build-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Use NodeJS 18'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Restore Cypress Binary
        uses: actions/cache/restore@v3
        id: restore-cypress
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
      - name: 'Setup github npm registry' # # Add the gh registry to npm config
        run: |
          npm set @elylucas:registry=https://npm.pkg.github.com/elylucas
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_GITHUB_TOKEN }}"
      - name: Install dependencies
        run: |
          npm install
      - name: Save Cypress Binary
        if: steps.restore-cypress.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
      - name: Run Linting
        run: npm run lint
      - name: Build app
        run: |
          npm run build
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build-folders
          if-no-files-found: error
          path: |
            packages/**/dist
            packages/**/build
            