name: Build and Test

# on: push

on:
  pull_request:
    types: [opened, synchronize]

env:
  PACKAGE_GITHUB_TOKEN: ${{ secrets.PACKAGE_GITHUB_TOKEN }}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout' # Download code from the repository
        uses: actions/checkout@v3 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags
      - name: 'Use NodeJS 18' # Setup node using version 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: 'Setup npm' # Add our registry to npm config
        run: | # Custom action
          npm set @elylucas:registry=https://npm.pkg.github.com/elylucas
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_GITHUB_TOKEN }}"
      - name: Install dependencies
        run: |
          npm install
      - name: Build app
        run: |
          npm run build
