name: Checks
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout" # Download code from the repository
      uses: actions/checkout@v4 # Public action
      with:
        fetch-depth: 0 # Checkout all branches and tags

    - name: "Use NodeJS 18" # Setup node using version 14
      uses: actions/setup-node@v3 # Public action
      with: 
        node-version: '18'
    - name: "Setup npm" # Add our registry to npm config
      run: | # Custom action
        npm set @elylucas:registry=https://npm.pkg.github.com/elylucas
        npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
    - name: Install dependencies
      run: | # Install and link dependencies
        npm ci