name: Main

on:
  push:
    branches:
      - '*'
      - '!main'
      - '!development'
      - '!next'
  pull_request:
    types: [closed]
    branches:
      - development
      - main
      - next
  workflow_dispatch:

env:
  PACKAGE_GITHUB_TOKEN: ${{ secrets.PACKAGE_GITHUB_TOKEN }}

jobs:
  install-build:
    uses: ./.github/workflows/build.yaml
  check:
    needs: install-build
    uses: ./.github/workflows/check.yaml
  publish:
    needs: [install-build, check]
    if: github.ref_name == 'main' || github.ref_name == 'development' || github.ref_name == 'next'
    permissions:
      contents: write
    uses: ./.github/workflows/publish.yaml
    secrets:
      PACKAGE_GITHUB_TOKEN: ${{ secrets.PACKAGE_GITHUB_TOKEN }}
