name: Publish packages

on:
  workflow_call:
    secrets:
      PACKAGE_GITHUB_TOKEN:
        required: true

env:
  PACKAGE_GITHUB_TOKEN: ${{ secrets.PACKAGE_GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    if: github.event.pull_request.merged == true # Condition
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout' # Download code from the repository
        uses: actions/checkout@v3 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags
      - name: 'Use NodeJS 18' # Setup node using version 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: 'Setup npm' # Add our registry to npm config
        run: | # Custom action
          npm set @elylucas:registry=https://npm.pkg.github.com/elylucas
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_GITHUB_TOKEN }}"
      - name: Install dependencies
        run: |
          npm install
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build-folders
      - name: 'Version and publish' # Interesting step
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "PubBot on belalf of (${{ github.actor }})"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          if [ ${{ github.ref }} = development ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid alpha --yes --no-private --no-changelog --no-git-tag-version
          else
            npx lerna version --conventional-commits --conventional-graduate --yes --no-private --create-release github
          fi

          npx lerna publish from-git --yes

          if [ ${{ github.ref }} = main ]; then
            git checkout development
            git rebase main
            git push origin development
          fi
