name: Run Tests

on: workflow_call

env:
  PACKAGE_GITHUB_TOKEN: ${{ secrets.PACKAGE_GITHUB_TOKEN }}

jobs:
  component-tests:
    runs-on: ubuntu-latest
    # needs: install-build-check
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Use NodeJS 18'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: 'Setup github npm registry' # Add the gh registry to npm config
        run: |
          npm set @elylucas:registry=https://npm.pkg.github.com/elylucas
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_GITHUB_TOKEN }}"
      - name: Restore Cypress Binary
        uses: actions/cache/restore@v3
        id: restore-cypress
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
      - name: Install dependencies
        run: |
          npm install
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build-folders
      - name: Run CT Tests
        run: npm run test:component
